### ISSUE TITLE
UnicodeDecodeError: 'CP_UTF8' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page

### ISSUE THREAD

**Issue by 1099446868** [Zageku/DNF_pvf_python#11]
提示这个 UnicodeDecodeError: 'CP_UTF8' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page

**Comment by Zageku** [comment]
打开控制面板，选择时钟和区域，点击区域，选择管理，更改系统区域设置，取消使用Beta版后点击确定并重新启动即可。
https://blog.csdn.net/dream6985/article/details/126074412

**Comment by 1099446868** [comment]
你好，我按照这个设置，重启后并没有解决这个问题哦，这里贴一下具体的报错：
 python36\python_pkgTool.exe python36\pkgEditLauncher.py
Traceback (most recent call last):
  File "python36\pkgEditLauncher.py", line 80, in <module>
    import dnfpkgtool.__main__ as main
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "F:\GameVM\dnf86\gm\python36\dnfpkgtool\__main__.py", line 26, in <module dnfpkgtool.__main__>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "F:\GameVM\dnf86\gm\python36\dnfpkgtool\cacheManager.py", line 835, in <module dnfpkgtool.cacheManager>
  File "F:\GameVM\dnf86\gm\python36\dnfpkgtool\cacheManager.py", line 804, in loadItems2
  File "json\__init__.py", line 296, in load
  File "codecs.py", line 321, in decode
UnicodeDecodeError: 'CP_UTF8' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
