### ISSUE TITLE
Linux和python3.11支持：更改图标，从ico改为png

### ISSUE THREAD

**Issue by NeroBlackstone** [Zageku/DNF_pvf_python#6]
在linux下运行会报：

```
nero@nero-90m2cto1ww ~/D/g/DNF_pvf_python (main) [1]> /bin/python /home/nero/Documents/github/DNF_pvf_python/dnfpkgto
ol/__main__.py
高清缩放失败
Traceback (most recent call last):
  File "/home/nero/Documents/github/DNF_pvf_python/dnfpkgtool/__main__.py", line 4417, in <module>
    run()
  File "/home/nero/Documents/github/DNF_pvf_python/dnfpkgtool/__main__.py", line 4402, in run
    app = GuiApp(root)
          ^^^^^^^^^^^^
  File "/home/nero/Documents/github/DNF_pvf_python/dnfpkgtool/__main__.py", line 1082, in __init__
    self._build()
  File "/home/nero/Documents/github/DNF_pvf_python/dnfpkgtool/__main__.py", line 1170, in _build
    self.w.iconbitmap(IconPath)
  File "/usr/lib/python3.11/tkinter/__init__.py", line 2136, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "config/ico.ico" not defined
```

修复的步骤是：
1.  config文件夹，ico转成png
``` shell
convert ico.ico ico.png
```
2.  `__main__.py`
```
# self.w.iconbitmap(IconPath)
self.w.call('wm', 'iconphoto', self.w._w, tk.PhotoImage(file=IconPath))
```

**Comment by NeroBlackstone** [comment]
close #8
